README.md, RELEASE_NOTES.md, paket.dependencies, paket.lock, samples/OptionAnalyzer/Library.fs, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.Client.fs, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.fs
When the SDK runs analyzers, it swallows all errors making it impossible for FSAC to know which analyzer is problematic and makes troubleshooting harder. This PR addresses this issue by allowing the analyzers to be (optionally) named via the attribute like this `[<Analuzer "AnalyzerName">]`. I added a new function to run the analyzers of this signature:
```fs
val runAnalyzersSafely : Context -> AnalysisResult list
```
Where each `AnalysisResult` is the result of each registered analyzer and is defined as follows:
```fs
type AnalysisResult = {
AnalyzerName : string
Output : Result<Message list, exn>
}
```
This way, we will be able to identify which analyzer wasn't able to run successfully and why (cc @baronfel) 
This is also preparation for fixing #8 which required the analyzers to be …
=> Named analyzers and better error handling

src/FSharp.Analyzers.Cli/Program.fs
With some shells and color schemes, just setting the foreground color to white might not be the best UX.
So this PR uses the original foreground color for normal output and also sets the color back to its original value.
=> respect the original foreground color of the console

src/FSharp.Analyzers.Cli/Program.fs, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.Client.fs
It can be very confusing when your analyzer is targeting the wrong SDK and gets loaded anyway by the cli tool. I propose to enforce using the correct version instead.
=> Verify sdk version

src/FSharp.Analyzers.Cli/Program.fs, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.fs
To make a lot of interesting analyzers possible, we need a bit more information in the context.
So let's add the symbol uses to it.
=> Add symbol uses to Context

.github/workflows/ci.yml, .github/workflows/release.yml
- Extract's releasing from CI yaml so we can do github releases from changelogs
- Fixes the duplicate running of CI on PRs
=> Extract release from ci yml

src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.Client.fs
Now with the filter/error reporting regarding mismatched referenced SDK versions from [72](https://github.com/ionide/FSharp.Analyzers.SDK/pull/72), loading and processing the SDK dll itself is not a good idea as the `Array.find` call in the filter throws with it.
=> don't process SDK dll itself

.github/workflows/ci.yml, Directory.Packages.props, src/FSharp.Analyzers.Cli/packages.lock.json
We need this to let the new version of FCS and projinfo align with each other.
=> update to projinfo 0.62 to fix runtime failure

src/FSharp.Analyzers.Cli/Program.fs
fixes #78 
Let the analyzer decide whether to process .fsi files or not
=> Don't filter out .fsi files

.config/dotnet-tools.json, docs/content/Dual Analyzer.fsx, docs/content/Getting Started.fsx, docs/content/Programmatic access.fsx, docs/index.md, docs/style.css, docs/tooltips.js, samples/OptionAnalyzer/Library.fs, src/FSharp.Analyzers.Cli/Program.fs, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.Client.fs, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.Client.fsi, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.fs, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.fsi, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.fsproj
A slight restructure of the `Context` type.
I think for now it should really expose all the base FCS primitives so people can do everything they need.
I've added some convenient members and we can expand upon that later.
I'm not quite sure yet about `CheckProjectResults: Async<FSharpCheckProjectResults>` yet.
As in should it be wrapped in `lazy` as well?
I quite like that `GetAllEntities`, `AllSymbolUses` and `SymbolUsesOfFile` are more on a demand basis.
Not all analyzers will require this.
Let me know what you think.
=> Revisit Context type

samples/OptionAnalyzer/Library.fs, src/FSharp.Analyzers.Cli/Program.fs, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.Client.fs, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.fs, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.fsi
I was having some issues with the context being created for signature files.
`TypedTree` should be optional in this regard.
=> Make TypedTree optional in CliContext.

README.md, docs/content/Getting Started.fsx, docs/index.md, docs/style.css
All code samples should really be ported to a `.fsx` file in the docs, that way they are easier to stay up to date. And I also want to avoid duplicating the docs.
=> Extract any duplicatish code from the main README.

CHANGELOG.md, docs/content/Programmatic access.fsx, src/FSharp.Analyzers.Cli/Program.fs, src/FSharp.Analyzers.SDK.Testing/FSharp.Analyzers.SDK.Testing.fs, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.Client.fs, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.Client.fsi
Example usage:
```shell
.\src\FSharp.Analyzers.Cli\bin\Debug\net6.0\FSharp.Analyzers.Cli.exe --analyzers-path "C:\Users\nojaf\Projects\fantomas\.analyzerpackages\g-research.fsharp.analyzers\0.1.1\lib\net6.0" --project "C:\Users\nojaf\Projects\FSharp.Analyzers.SDK\src\FSharp.Analyzers.SDK\FSharp.Analyzers.SDK.fsproj" --exclude-analyzer "UnionCaseAnalyzer" --verbose
```
```
Info : Running in verbose mode
Info : Fail On Warnings: []
Info : Ignore Files: []
Info : Loading analyzers from C:\Users\nojaf\Projects\fantomas\.analyzerpackages\g-research.fsharp.analyzers\0.1.1\lib\net6.0
Info : Excluding UnionCaseAnalyzer from G-Research.FSharp.Analyzers, Version=0.1.1.0, Culture=neutral, PublicKeyToken=null
Info : Excluding UnionCaseAnalyzer from G-Research.FSharp.Analyzers, Version=0.1.1.0, …
```
=> Exclude analyzers

CHANGELOG.md, src/FSharp.Analyzers.Cli/Program.fs
=> support multiple project parameters in the Cli tool

src/FSharp.Analyzers.SDK.Testing/FSharp.Analyzers.SDK.Testing.fs, src/FSharp.Analyzers.SDK.Testing/FSharp.Analyzers.SDK.Testing.fsi
Why should we do this?
It's very easy to construct tests which aren't valid F# but still produce tree structures that are passed on via the context. 
That could erroneously be processed by analyzers and give wrong test results.
Another pitfall is to use an API in the testcase, which isn't available in netstandard.
If the analyzer author writes a test for that, his analyzer could process the information from the context even though it wouldn't compile in the real world due to a missing overload in the netstandard API.
So, to make the analyzer/test author aware of errors in his testcases, we throw an exception with diagnostics of error severity.
=> Throw custom exception with diagnostics if the severity is Error

.github/workflows/release.yml
`log_entry` was renamed to `changes`.
I hope this is the reason, why our automatic creation of changelogs for releases stopped to work.
See https://github.com/mindsers/changelog-reader-action/blob/d8f4048265c49bd76854ce1faa024467ca39bd7e/CHANGELOG.md?plain=1#L70
If the next release still doesn't work, we might need to play with the validation_level as we don't really do strict semver regarding the CHANGELOG entries.
But let's see, I think this is all we need.
=> Fix creation of changelog for releases

CHANGELOG.md, Directory.Packages.props, src/FSharp.Analyzers.Cli/FSharp.Analyzers.Cli.fsproj, src/FSharp.Analyzers.Cli/Program.fs, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.Client.fs, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.Client.fsi, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.fs, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.fsi
Fixes #22.
The result sarif looks like:
```json
{
"$schema": "https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.6.json",
"version": "2.1.0",
"runs": [
{
"results": [
{
"ruleId": "GRA-STRING-001",
"ruleIndex": 0,
"message": {
"text": "The usage of String.EndsWith with a single string argument is discouraged. Signal your intention explicitly by calling an overload."
},
"locations": [
{
"physicalLocation": {
"artifactLocation": {
"uri": "file:///C:/Users/nojaf/Projects/graph-sample/B.fs"
},
"region": {
"startLine": 3,
"endLine": 3,
"endColumn": 17
}
}
}
]
},
{
"ruleId": "GRA-STRING-001",
"ruleIndex": 0,
"message": {
"text": "The usage of String.EndsWith with a single string argument is discouraged. Signal your intention explicitly by calling an overload."
},
"locations": [
{ …
```
=> Add report flag to CLI tool

docs/content/Running during CI.md, docs/content/Unit Testing.fsx
Basic documentation for what we did in https://github.com/fsprojects/fantomas/pull/2962
=> Add basic documentation for CI support.

CHANGELOG.md, Directory.Packages.props, docs/content/Getting Started.fsx, src/FSharp.Analyzers.Cli/Program.fs, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.fs, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.fsi
Helps in https://github.com/ionide/FSharp.Analyzers.SDK/issues/124
I think it currently is a bit of a lie that we say:
While FCS has:
I'm in favour of locking both FCS and FSharp.Core down.
=> Exit the commandline tool if the version of FSharp.Core cannot be loaded

CHANGELOG.md, src/FSharp.Analyzers.Cli/Program.fs
The use-case for this is:
```
<Target Name="Analyzer"
DependsOnTargets="Restore;ResolveAssemblyReferencesDesignTime;ResolveProjectReferencesDesignTime;ResolvePackageDependenciesDesignTime;FindReferenceAssembliesForReferences;_GenerateCompileDependencyCache;_ComputeNonExistentFileProperty;BeforeBuild;BeforeCompile;CoreCompile">
<PropertyGroup>
<AnalyzersPath>&quot;$(PkgNojaf_Chad_Analyzers)\analyzers\dotnet\fs&quot;</AnalyzersPath>
</PropertyGroup>
<Exec Command="dotnet tool restore" />
<Exec Command="dotnet fsharp-analyzers --fsc-args &quot;@(FscCommandLineArgs)&quot; --analyzers-path $(AnalyzersPath) --verbose --report $(MSBuildProjectDirectory)\analysis.sarif" />
</Target>
```
We will add more end-user / getting starting documentation shortly.
=> Accept direct fsc arguments as input.

docs/content/Getting Started.fsx
Adds additional info you want to have when creating the nuget packages.
=> Add documentation on msbuild props when packaging.

CHANGELOG.md, src/FSharp.Analyzers.Cli/Program.fs, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.Client.fs
Fixes https://github.com/ionide/FSharp.Analyzers.SDK/issues/132.
@dawedawe I also changed the version check slightly so we don't need to bump the GR analyzers for this release.
=> Create sarif folder if it does not exist

CHANGELOG.md, src/FSharp.Analyzers.Cli/Program.fs
- mark all CLI args as unique
- print messages when using FSC args, too
- support remapping of all severity levels
- support passing of multiple --project flags
- support passing of multiple --analyzers-path flags
=> Support remapping all severity levels

CHANGELOG.md, src/FSharp.Analyzers.Cli/Program.fs
fixes #141 
This PR also removes the doubled transformation to an absolute path.
Instead of continuing with other valid projects paths, this PR takes the decision to fail completely if at least one bad path was given. 
My thinking is that the message about the invalid path could be overseen by the users. Meaning the analyzers are effectively running for just a subset of the solution while the user thinks all of the projects are analyzed. That could mean the user misses critical analyzer results for projects that weren't analyzed because of a bad path.
=> check --project arguments if file exists

.config/dotnet-tools.json, CHANGELOG.md, src/FSharp.Analyzers.Cli/Program.fs
Fixes #154.
This now allows me to open a sarif in Rider 🤘
=> Improve sarif

CHANGELOG.md, src/FSharp.Analyzers.Cli/Program.fs
A follow-up of https://github.com/ionide/FSharp.Analyzers.SDK/pull/155.
This helps when you can execute `dotnet fsharp-analyzers` inside the `repo-root/src/Project` directory but want to report all the file paths relative to `repo-root`.
=> Add code-root flag

CHANGELOG.md, src/FSharp.Analyzers.Cli/Program.fs
@baronfel Is that roughly what you had in mind in #84 ?
With it we can do things like:
```shell
-p Configuration=Release -p DefineConstants="MYDEF" ...
```
=> Support MSBuild properties on the CLI

CHANGELOG.md, src/FSharp.Analyzers.SDK/ASTCollecting.fs, src/FSharp.Analyzers.SDK/ASTCollecting.fsi
=> Extend signature AST walking

CHANGELOG.md, src/FSharp.Analyzers.Cli/Program.fs
When the design time build failed for some reason, you don't want to try and load empty arguments.
=> Raise clear error if empty FSC arguments were passed.

CHANGELOG.md, docs/content/Getting Started Using.md, src/FSharp.Analyzers.Build/CHANGELOG.md, src/FSharp.Analyzers.Build/build/FSharp.Analyzers.Build.targets, src/FSharp.Analyzers.Build/buildMultitargeting/FSharp.Analyzers.Build.targets
Alas, I must shatter my dream of reusing the `fsc` arguments provided by MSBuild.
I noticed some drawbacks when doing a `DesignTimeBuild` for projects that have project references.
Let us take `Fantomas.Client.fsproj` and `Fantomas.Client.Tests.fsproj` as example:
- Performing the design time build for `Fantomas.Client.Tests.fsproj` will trigger a build for `Fantomas.Client.fsproj` as well. However, this won't produce a binary for `Fantomas.Client`, while `Fantomas.Client.Tests` does depend on its existence from the fsc args perspective.
- Because `Fantomas.Client.Tests` already built `Fantomas.Client` (without producing a binary), `CoreCompile` will be skipped when we try and do the design time build for `Fantomas.Core` and thus `FscCommandLineArgs` will not be populated. I believe this …
=> Remove AnalyzeFSharpProjectUsingFscArgs

src/FSharp.Analyzers.SDK.Testing/FSharp.Analyzers.SDK.Testing.fs
I was having a go at building the SDK locally to test some things, and the build script failed to run the tests with errors like
```
MSBuild version 17.8.3+195e7f5a3 for .NET
MSBUILD : error MSB1009: Project file does not exist.
Switch: Webb\AppData\Local\Temp\FSharp.Analyzers.SDK.BinLogCache\v0.21.0.0_net7.0_Newtonsoft.Json_13.0.3_Fantomas.FCS_6.2.0.binlog
StdErr:
Exception:
CliWrap.Exceptions.CommandExecutionException: Command execution failed because the underlying process (dotnet.exe#12396) returned a non-zero exit code (1).
Command:
dotnet build -bl:C:\Users\Richard Webb\AppData\Local\Temp\FSharp.Analyzers.SDK.BinLogCache\v0.21.0.0_net7.0_Newtonsoft.Json_13.0.3_Fantomas.FCS_6.2.0.binlog
```
As it happens, the path to my user/temp directory has a space in it, and the ```Switch: …
```
=> Wrap the path to the binlog in quotes when building a test project

src/FSharp.Analyzers.Cli/FSharp.Analyzers.Cli.fsproj
Quite trivial and i'm not sure what the text should be, it's just that whenever I look at listings on nuget.org that don't have a description set, the default 'Package Description' text sticks out to me - e.g.
=> Add a description to the Cli tool nuget package

Directory.Build.props
refs https://github.com/ionide/FSharp.Analyzers.SDK/issues/33 where the license seems to not be getting applied to the packages due to the condition.
Alternatively the suggestion in https://github.com/ionide/FSharp.Analyzers.SDK/issues/33#issuecomment-1823079531 to move the logix into a directory.build.targets also seems to work, so I can do whichever one is prefered.
=> Remove the condition on setting PackageLicenseExpression/PackageTags in directory.build.props

src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.fsproj
With this, we can use the debug build on some more complex code bases like fsharp itself.
=> always emit TailCalls to not overflow the stack

src/FSharp.Analyzers.Cli/Program.fs
=> Fill in arg of log

src/FSharp.Analyzers.Build/FSharp.Analyzers.Build.csproj
As #172 except for FSharp.Analyzers.Build:
refs the current default description field:
=> Add a package description to FSharp.Analyzers.Build

src/FSharp.Analyzers.Build/FSharp.Analyzers.Build.csproj
=> Retarget FSharp.Analyzers.Build from netstandard1.0 to netstandard2.0

src/FSharp.Analyzers.Build/CHANGELOG.md
Merging this one in won't publish the package just yet.
But we probably want to have it published when we ship the next SDK version.
=> Bump version to 0.3.0

CHANGELOG.md, src/FSharp.Analyzers.Cli/Program.fs, src/FSharp.Analyzers.SDK.Testing/FSharp.Analyzers.SDK.Testing.fs, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.Client.fs, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.Client.fsi
The tool currently silently swallows this sort of error.
This change is backward incompatible. Is that OK?
=> Fail the tool when analyzers fail to load

CHANGELOG.md, docs/content/Dual Analyzer.fsx, docs/content/Getting Started Writing.fsx, samples/OptionAnalyzer/Library.fs, src/FSharp.Analyzers.Cli/Program.fs, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.fs, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.fsi
We currently export the DU case `Error`, which clashes with FSharp.Core's `Result.Error`. This change means we never conflict with FSharp.Core. The change is source-incompatible, so it will require a release note.
=> Add RequireQualifiedAccess to Severity type

src/FSharp.Analyzers.Cli/FSharp.Analyzers.Cli.fsproj, src/FSharp.Analyzers.Cli/Program.fs, src/FSharp.Analyzers.Cli/Result.fs, src/FSharp.Analyzers.SDK.Testing/FSharp.Analyzers.SDK.Testing.fs, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.fs, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.fsi
Motivation is https://github.com/Smaug123/fsharp-prattparser/actions/runs/7619221208/job/20751901249 , which succeeded despite the output being as follows:
```
info: Running in verbose mode
info: Treat as Hints: []
info: Treat as Info: []
info: Treat as Warning: []
info: Treat as Error: [GRA-IMMUTABLECOLLECTIONEQUALITY-001, GRA-INTERPOLATED-001, GRA-JSONOPTS-001, GRA-LOGARGFUNCFULLAPP-001, GRA-STRING-001, GRA-STRING-002, GRA-STRING-003, GRA-TYPE-ANNOTATE-001, GRA-UNIONCASE-001, GRA-VIRTUALCALL-001]
info: Exclude Files: []
info: Include Files: []
info: Loading analyzers from /home/runner/work/fsharp-prattparser/fsharp-prattparser/.analyzerpackages/g-research.fsharp.analyzers/0.7.0/
info: Registered 12 analyzers from 1 dlls
error: Checking of file …
```
=> Fail the tool if any analysis fails

src/FSharp.Analyzers.Cli/Program.fs
(I seem to be hitting every possible way to hold this tool wrongly!)
I think it's more useful to fail when there are no analyzers registered, than to return "OK, did nothing". I suspect it's going to be *very* unusual to intentionally register no analyzers.
=> Fail on no analyzers registered

CHANGELOG.md, Directory.Packages.props
This is required to get FSAC updated because of the explicit-match constraint from this repo.
=> bump FCS and FSC to 8.0.200 now that they've been released

CHANGELOG.md, src/FSharp.Analyzers.Cli/CustomLogging.fs
refs #215 
Printing the 0m control code looks like how Fargo resets the colour, and that seems to work for me here on Windows (cmd.exe and windows terminal).
I haven't tested it on any other OS yet, and not sure if there is a need to reset Console.ForegroundColor as well as printing the codes.
=> Reset the console foreground colour with control codes

CHANGELOG.md, src/FSharp.Analyzers.Cli/Program.fs
=> Only Analyze projects passed in via CLI

.github/workflows/ci.yml, .github/workflows/release.yml
I just noticed this warning in the build results:
=> Update the Github checkout and setup-dotnet actions from v3 to v4

.config/dotnet-tools.json, .github/workflows/ci.yml, .github/workflows/release.yml, Directory.Packages.props, build.fsx, docs/content/Unit Testing.fsx, global.json, samples/OptionAnalyzer.Test/OptionAnalyzer.Test.fsproj, samples/OptionAnalyzer/OptionAnalyzer.fsproj, src/FSharp.Analyzers.Cli/FSharp.Analyzers.Cli.fsproj, src/FSharp.Analyzers.SDK.Testing/FSharp.Analyzers.SDK.Testing.fsproj, src/FSharp.Analyzers.SDK/ASTCollecting.fs, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.fsproj
refs https://github.com/ionide/FSharp.Analyzers.SDK/issues/221
Note: I'm trying to learn a bit more about how this stuff works, so I'm not certain how the new null AST bits like ```SynType.WithNull``` should be handled
=> Update FSharp.Compiler.Service and FSharp.Core to the '9' versions

Directory.Packages.props
When I was doing https://github.com/G-Research/fsharp-analyzers/pull/85 I got a security warning from Visual Studio about a transitive dependency
FSharp.Analyzers.SDK.Testing -> Microsoft.Extensions.Logging.Console -> System.Text.Json 6.0.0
Because System.Text.Json 6.0.0 has known CVEs.
So I wondered if it would be useful to update Microsoft.Extensions.Logging.Console to 6.0.1, which has removed the NuGet dependency on System.Text.Json in the .NET 6.0 TFM so it just uses the in-box version.
This shouldn't effect the version of Microsoft.Extensions.Logging.Abstractions used by the SDK lib itself, just the console lib used by the Testing and Cli packages.
=> Update Microsoft.Extensions.Logging.Console to 6.0.1

src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.Client.fs
In VSCode I currently have the following settings to enable analyzers in the IDE.
```json
{
"FSharp.enableAnalyzers": true,
"FSharp.analyzersPath": [
"packages/Analyzers"
],
}
```
When switching between branches of my codebase, if there are different versions of my analyzers, I will get an error during the paket restore step due to the files being used. My current workaround is to manually delete the folder listed above and then restore my solution.
In order to circumvent this, there appears to be a setting in the package we are consuming to allow loading the assemblies into memory. Looking through the code, it does not appear we are using this setting nor is it overriding any hot reload functionality.
[CreateFromAssemblyFile](https://github.com/natemcmaster/DotNetCorePlugins/blob/a6094157 …
=> Prevent File Locking Issue

docs/content/Running during CI.md, src/FSharp.Analyzers.Cli/Program.fs
This adds a new CLI parameter, `--output-format`, which can be set to either `default` or `github`.
The `default` option preserves the current way to print analyzer results to stdout.
The `github` option instead prints the analyzer results in a format that can be understood as a code annotation by GitHub Actions ([reference](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions)).
This feature allows users without a GitHub Advanced Security subscription to get nicely formatted analyzer results in CI for private repositories.
Here are some (lightly censored) screenshots of what it looks like in a real code base.
In the "Files changed" section of a pull request:
In the workflow log view:
The main limitation of this is that …
=> Add GitHub logging output format

Directory.Packages.props, docs/index.md, global.json, samples/BadOptionUsage.fsx, src/FSharp.Analyzers.Cli/Program.fs
=> 234 support script files

src/FSharp.Analyzers.Cli/Program.fs, src/FSharp.Analyzers.SDK.Testing/FSharp.Analyzers.SDK.Testing.fs, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.fs, src/FSharp.Analyzers.SDK/FSharp.Analyzers.SDK.fsi
refs https://github.com/ionide/ionide-analyzers/issues/147
Based in discussions in https://github.com/ionide/ionide-analyzers/issues/147, where there are currently issues due to ```FSharpProjectOptions``` not being accessible in Ionide when the transparent compiler is enabled
=> Add project options to analyzer contexts

src/FSharp.Analyzers.SDK/TASTCollecting.fs
Just a thought when playing with things - looks like creating these sets inside ```visitDeclaration``` creates a substantial number of lists and sets, and as the contents are constant it doesn't seem like it should need to create them more than once?
Running a memory profile of the SDK cli tool against one of my projects got this before:
and this after:
=> Move membersToIgnore/exprTypesToIgnore out of visitDeclaration()

samples/OptionAnalyzer/Library.fs
=> Add EditorContext to OptionAnalyzer

src/FSharp.Analyzers.Cli/CustomLogging.fs, src/FSharp.Analyzers.Cli/Program.fs
Closes #245 
```bash
dotnet run -f net8.0 -- --project ../../samples/OptionAnalyzer/OptionAnalyzer.fsproj --analyzers-path ../../artifacts/bin/OptionAnalyzer/debug
[20:18:43.021] critical: FSharp.Analyzers.Cli could not find System.Runtime, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a. If you're using a preview version of the .NET SDK, you may need to set DOTNET_ROLL_FORWARD_TO_PRERELEASE=1 in your environment before running this tool.
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
at …
```
=> Add logging about System.Runtime load exceptions

.config/dotnet-tools.json, docs/content/getting-started/MSBuild.md, samples/MsBuildExample/MsBuildExample.fsproj, samples/MsBuildExample/Program.fs, src/FSharp.Analyzers.Build/build/FSharp.Analyzers.Build.targets
This kind of revitalizes https://github.com/ionide/FSharp.Analyzers.SDK/pull/164, but this takes a slightly different approach.
- Instead of trying to do a DesignTimeBuild within msbuild, it will try to run after a `CoreCompile`/`AfterBuild` target actually runs.
- This uses the `RunAnalyzer` or `RunAnalyzersDuringBuild` (see [Roslyn variables](https://learn.microsoft.com/en-us/visualstudio/code-quality/disable-code-analysis?view=vs-2022#net-framework-projects)) to determine if it should run or not.
- This will skip the `FsharpAnalyzerAfterBuild` target if `CoreCompile` does not produce FscArgs. However someone can use `FSharpAnalyzers_AlwaysRunAfterBuild` to always run after a build, still using Ionide.ProjInfo as before to do design time builds.
=> Utilize Fsc args in msbuild analyze if available

README.md
The build is using artifact output, so the binaries get put under ./artifacts rather than ./samples
=> Fix the path to the OptionsAnalyzer binary in the readme.
